---
- name: ---
- name: Configure Ubiquiti LiteBeam with MAC ACL
  hosts: litebeam_hosts
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: FutureBroadbandAS400497
    ansible_ssh_pass: FutureBroadbandAS400497
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    default_system_cfg_path: /tmp/system.cfg  # Ensure this file exists on your local machine
  
  tasks:
    - name: Check if default system.cfg exists on localhost
      stat:
        path: "{{ default_system_cfg_path }}"
      delegate_to: localhost
      register: default_system_cfg_stat

    - name: Fail if default system.cfg does not exist on localhost
      fail:
        msg: "The default system.cfg file does not exist at {{ default_system_cfg_path }} on localhost."
      when: not default_system_cfg_stat.stat.exists

    - name: Extract MAC address
      raw: "ifconfig eth0 | grep 'HWaddr' | awk '{print $5}'"
      register: mac_address_output

    - name: Display the MAC address
      debug:
        msg: "MAC address is {{ mac_address_output.stdout.strip() }}"

    - name: Read default system.cfg using raw command on localhost
      local_action: command cat {{ default_system_cfg_path }}
      register: default_system_cfg_output

    - name: Generate new MAC ACL entry
      set_fact:
        new_mac_acl_entry: |
          wireless.1.mac_acl.{{ item.index }}.mac={{ item.mac }}
          wireless.1.mac_acl.{{ item.index }}.status=enabled
      with_items:
        - { index: 80, mac: "{{ mac_address_output.stdout.strip() }}" }  # Update the index as per the existing number of ACL entries

    - name: Append new MAC ACL entry to system.cfg content
      set_fact:
        updated_system_cfg: "{{ default_system_cfg_output.stdout + '\n' + new_mac_acl_entry }}"

    - name: Write updated system.cfg to a temporary file on localhost
      copy:
        content: "{{ updated_system_cfg }}"
        dest: /tmp/system.cfg.updated
      delegate_to: localhost

    - name: Upload updated system.cfg to device
      copy:
        src: /tmp/system.cfg.updated
        dest: /tmp/system.cfg

    - name: Apply the updated system.cfg
      raw: "cfgmtd -w -p /etc/"

    - name: Save the configuration
      raw: "save"

    # Uncomment the following lines if a reboot is required
    # - name: Reboot device
    #   raw: "reboot"
