---
- name: SSH into Ubiquiti LiteBeam
  hosts: litebeam_hosts
  gather_facts: no
  tasks:
    - name: SSH into LiteBeam
      ansible.builtin.shell: ssh admin@{{ ansible_host }} -o StrictHostKeyChecking=no
      vars:
        ansible_ssh_pass: FutureBroadbandAS400497

  tasks:
    - name: Run a command on LiteBeam
      ansible.builtin.shell: "ping -c 4 1.1.1.1"
