---
- name: SSH into Ubiquiti LiteBeam
  hosts: litebeam_hosts
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: FutureBroadbandAS400497
    ansible_ssh_pass: FutureBroadbandAS400497
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Modify configuration file using sed
      raw: sed -i 's/^wpasupplicant.profile.1.network.1.psk=.*/wpasupplicant.profile.1.network.1.psk=FutureBroadbandAS400497/' /tmp/system.cfg