---
- name: SSH into Ubiquiti LiteBeam
  hosts: litebeam_hosts
  gather_facts: no
  tasks:
    - name: SSH into LiteBeam
      ansible.builtin.command: ssh admin@{{ ansible_host }} -o StrictHostKeyChecking=no
#      vars:
#        ansible_ssh_pass: FutureBroadbandAS400497

