---
- name: SSH into Ubiquiti LiteBeam
  hosts: litebeam_hosts
  gather_facts: no
  vars:
    ansible_user: admin
    ansible_password: FutureBroadbandAS400497
    ansible_ssh_pass: FutureBroadbandAS400497
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Modify the WPA Pre-Shared Key
      raw: sed -i 's/^wpasupplicant.profile.1.network.1.psk=.*/wpasupplicant.profile.1.network.1.psk=FutureBroadbandAS400497/' /tmp/system.cfg
    - name: Modify aaa.1.wpa.psk=
      raw: sed -i 's|^aaa.1.wpa.psk=.*|aaa.1.wpa.psk=FutureBroadbandAS400497|' /tmp/system.cfg
    - name: Modify the UNMS key
      raw: sed -i 's|^unms.uri=.*|unms.uri=wss://portal.futurebroadband.net:443+gw2qBhwpdlJd1HKqPhX13PWn90Ld4kGt1trLyK5KknYAAAAA+allowUntrustedCertificate|' /tmp/system.cfg
    - name: Enable UNMS
      raw: sed -i 's|^unms.status=.*|unms.status=enabled|' /tmp/system.cfg
    - name: Change Radio Antenna Gain
      raw: sed -i 's|^radio.1.antenna.gain=.*|radio.1.antenna.gain=22|' /tmp/system.cfg
#    - name: Save config
#      raw: save
#    - name: Reboot CPE
#      raw: reboot