---
- name: Provision CPE Base Configuration
  hosts: litebeam_hosts
  gather_facts: no
  vars:
    ansible_user: ubnt
    ansible_password: ubnt
    ansible_ssh_pass: ubnt
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Modify the Wireless PSK (wpasupplicant.profile.1.network.1.psk) setting
      #become: yes
      replace:
        path: /tmp/system.cfg
        regexp: '^(wpasupplicant.profile.1.network.1.psk=).*$'
        replace: '\g<1>FutureBroadbandAS400497'