---
- name: Provision New CPE Inventory
  hosts: litebeam_hosts
  gather_facts: no
  vars:
    ansible_user: ubnt
    ansible_password: ubnt
    ansible_ssh_pass: ubnt
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Run ping command
      raw: ping -c 4 1.1.1.1