---
- name: Provision CPE Base Configuration
  hosts: litebeam_hosts
  gather_facts: no
  vars:
    ansible_user: ubnt
    ansible_password: ubnt
    ansible_ssh_pass: ubnt
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Modify configuration file using sed
      raw: |
        sed -i 's/^wpasupplicant.profile.1.network.1.psk=.*/wpasupplicant.profile.1.network.1.psk=FutureBroadbandAS400497/' /tmp/system.cfg